#ifndef KEYMAP_CONFIG_H
#define KEYMAP_CONFIG_H

#ifndef LED_BRIGHTNESS_DEFAULT
    #undef LED_BRIGHTNESS_DEFAULT
    #define LED_BRIGHTNESS_DEFAULT  (LED_BRIGHTNESS_HI / 2)
#endif

#define RGBLIGHT_COLOR_LAYER_0 0x7F, 0x7F, 0x7F
#define RGBLIGHT_COLOR_LAYER_1 0xFF, 0x00, 0x00 
#define RGBLIGHT_COLOR_LAYER_2 0x00, 0x00, 0xFF 

#endif